comment_width = 100
condense_wildcard_suffixes = true
hard_tabs = false
imports_granularity = "One"
group_imports = "One"
match_arm_blocks = false
match_block_trailing_comma = true
force_multiline_blocks = false
max_width = 120
newline_style = "Unix"
normalize_comments = false
overflow_delimited_expr = true
reorder_impl_items = true
reorder_modules = true
tab_spaces = 4
trailing_semicolon = false
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
