(function() {var implementors = {};
implementors["qapi_parser"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"qapi_parser/spec/struct.Data.html\" title=\"struct qapi_parser::spec::Data\">Data</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"qapi_parser/spec/enum.DataOrType.html\" title=\"enum qapi_parser::spec::DataOrType\">DataOrType</a>",];
implementors["qapi_qmp"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"qapi_qmp/struct.POWERDOWN.html\" title=\"struct qapi_qmp::POWERDOWN\">POWERDOWN</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"qapi_qmp/struct.STOP.html\" title=\"struct qapi_qmp::STOP\">STOP</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"qapi_qmp/struct.RESUME.html\" title=\"struct qapi_qmp::RESUME\">RESUME</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"qapi_qmp/struct.SUSPEND.html\" title=\"struct qapi_qmp::SUSPEND\">SUSPEND</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"qapi_qmp/struct.SUSPEND_DISK.html\" title=\"struct qapi_qmp::SUSPEND_DISK\">SUSPEND_DISK</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"qapi_qmp/struct.WAKEUP.html\" title=\"struct qapi_qmp::WAKEUP\">WAKEUP</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"qapi_qmp/struct.SPICE_MIGRATE_COMPLETED.html\" title=\"struct qapi_qmp::SPICE_MIGRATE_COMPLETED\">SPICE_MIGRATE_COMPLETED</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
